### ISSUE TITLE
Scroll lock? with menu on iPhone

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#1]
Summary:
When opening the menu on an iPhone, there are too many menu items to load on one screen, so the user needs to scroll down to view them all. The issue is that when the user does this, the app screen also scrolls, making this confusing for the user, and the active menu item jumps around, making it difficult to select another item.

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez this is FIXED please review this here http://inthought.pw and tell me if its working now on iphone devices. Please comment so will close this issue after that. 

Also will upload codes to git later.

Thanks

**Comment by rodolfomartinez** [comment]
Working.
