### ISSUE TITLE
Members Search - Advanced view - iPad issue

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#2]
**Summary:**
When viewing members/member_search.html on an iPad using safari, the Advanced Search button does not work, although it appears to work on a desktop.

**Comment by KPSbuttar** [comment]
@rodolfomartinez  Please Recheck this issue on ipad IT IS FIXED. Reply ASAP. Thanks

**Comment by rodolfomartinez** [comment]
fixed.
