### ISSUE TITLE
Lost Password Screen Styling

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#29]
**Summary:**
Please re-style this so that it looks almost the same as the login screen

**Comment by bartmika** [comment]
![screen shot 2018-02-17 at 10 07 11 am](https://user-images.githubusercontent.com/5767602/36342734-95edc9f8-13d0-11e8-8ef3-22fb12e03448.png)

Here is the screenshot of what I have implemented I have the following concerns.

1. I would like to have the logo branding in this screen somehow, I've made it look like this. If you can make it look like this or better, feel free.

2. The *password* and *repeat_password* fields are not good design for user experience. I need the following criteria, read below.

3. Please create a label for "password" input field saying "Please enter your password".

4. Please create a label for "repeat_password" input field saying "Please enter your password again.".

5. Under the "password" input field, please create a list of bullet points which are to indicate the requirements for the password. They'll have points like: (a) Please enter a single upper case character (b) Please enter a single special character like !, @, #, %, ^, etc (c) Please make sure to enter a password which is at minimum 5 characters long.

**Comment by KPSbuttar** [comment]
Hi sir @bartmika @rodolfomartinez This is Done.
All validations are added to Password Rest as well as to LOGIN screen Both pages are completed. Pleae review here: http://inthought.pw/password-reset.html
http://inthought.pw/

Thanks
