### ISSUE TITLE
Move "start" to "html" folder

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought#35]
@KPSbuttar Can you please move your code in **start** folder into the **html** folder. Please make sure each pages assets (ex: CSS or images) are placed into the **assets** folder.

**Comment by KPSbuttar** [comment]
Hi sir, hope you are well.

So this is done. Thanks!

**Comment by bartmika** [comment]
@KPSbuttar Perfect, now delete the "start" folder since we are not using it.

**Comment by KPSbuttar** [comment]
Its done
