### ISSUE TITLE
Members index page > Text Changes

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#42]
**Summary:**
Please make the following text changes:

**Change Add Description/Subtitle to:**
Add Member
**Change Search Description/Subtitle to:**
Search Members
**Change Edit Description/Subtitle to:**
Edit Members
**Change View Description/Subtitle to:**
View Active Members

**Associate Member List:**
Change heading to: Recent Associate Members:
and list 3 items

**Comment by KPSbuttar** [comment]
Its Done please review here: http://inthought.pw/members/
