### ISSUE TITLE
Team Index > Text Changes

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#48]
**Summary:**
Please make the following text changes:

**Page Title:**
Changes from Associate Members to: Team Members

**Change Add Description/Subtitle to:**
Add Member
**Change Search Description/Subtitle to:**
Search Members
**Change Edit Description/Subtitle to:**
Edit Members
**Change View Description/Subtitle to:**
View Members

**Associate Member List:**
Replace with a Jumbotron widget titled Announcements
Something like this
https://bootsnipp.com/snippets/bpKxb

**Comment by KPSbuttar** [comment]
Its done @rodolfomartinez  please check here: http://inthought.pw/team/#
