### ISSUE TITLE
Partner Index > Text Changes

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#53]
**Summary:**
Please make the following text changes:

**Change Page Title from Dashboard to:**
Partners

**Change Add Description/Subtitle to:**
Add Partner
**Change Search Description/Subtitle to:**
Search Partners
**Change Edit Description/Subtitle to:**
Edit Partners
**Change View Description/Subtitle to:**
View Active Partners

**Associate Member List:**
Change heading to: Recent Partners:
and list 3 items

**Comment by KPSbuttar** [comment]
Its done sir, please review here: http://inthought.pw/partners/#
