### ISSUE TITLE
Create /profile

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#61]
**Summary:**
Create Profile page using something like this:
https://bootsnipp.com/snippets/featured/user-profile-widget
but make all text and image bigger, replace website with phone number, remove date, add sub heading Skills: with skill 1, Skill 2, Skill 3 underneath, add a tag cloud under that.
Remove Social Button
Add a star rating field - make 4.5/5 stars filled in.

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir This is finally DONE created custom built Rating jquery script for both input and viewing purposes. Please review it here : http://inthought.pw/profile/

**Comment by bartmika** [comment]
@rodolfomartinez How does a user edit these field?

**Comment by rodolfomartinez** [comment]
@KPSbuttar in iphone the back to top does not display correctly (just shows as a small blue rectangle) and the star ratings do not display. Please see screencap
![cf66db96-010e-4833-b90f-fd89f48f31c0](https://user-images.githubusercontent.com/7537946/37492034-a99b96c0-2897-11e8-8511-83c630d628f3.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez please recheck if this error still their ?
