### ISSUE TITLE
Add Client Screen 4 - Confirmation

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#65]
**Summary:**
This should all be read only, and have say along the top
Please confirm these details before adding the client:
(all details from previous 4 screens should be here)
And along the bottom left an orange back button and along the bottom right a green Add button.

**Comment by bartmika** [comment]
1. Please include validation for the field

**Comment by rodolfomartinez** [comment]
@KPSbuttar please create two identical copies of this page, one called http://inthought.pw/clients/client_add_4.html and http://inthought.pw/clients/client_add_comm_4.html

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez This is DONE
Please review both residential and commercial confirmation pages here: http://inthought.pw/clients/client_add_4.html 
http://inthought.pw/clients/client_add_comm_4.html
