### ISSUE TITLE
Clients List - Notification

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought#67]
Please include a notification bar in the clients list page. Have a green, blue, grey and red bars. Have appropriate.

@rodolfomartinez FYI

**Comment by bartmika** [comment]
Hi @KPSbuttar, can you please focus your effort on finishing this ticket first? Thanks!

@rodolfomartinez FYI.

**Comment by rodolfomartinez** [comment]
@bartmika can you please elaborate? Not sure exactly what you mean.

**Comment by KPSbuttar** [comment]
@bartmika Hi sir so this gonna be new Client_list.html page under client index page. Can you please explain a little this page UI which need to create. Thanks

**Comment by bartmika** [comment]
Please see this link: http://www.binpress.com/app/jquery-notifications-plugin/1639

Basically I am looking for ways to provide GUI notifications, for example, you successfully created a client, I want to post a notification saying that the client was created.

**Comment by rodolfomartinez** [comment]
Thanks @bartmika .  @KPSbuttar can you please create something like this? I would prefer to not use this library if possible since the GPL license may not be compatible with our BSD license for InThought

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hello sir so much sorry for the delay this is done. Please review Notifications bars here: http://inthought.pw/clients/client_list.html

Also if you need icons at the starting of the text inside bars please tell me will add just like sample you shown above.

Thanks

**Comment by KPSbuttar** [comment]
This screen is DONE includes recent clients list also.

**Comment by bartmika** [comment]
That looks great @KPSbuttar ! Yes, let me see how a notification with font-awesome icon.
