### ISSUE TITLE
Client - Separate Personal and Business

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought#71]
Hi @KPSbuttar ,

May you please create a page when you click the "Add Client" that it takes you to a page similar like to "Reports" where you have a choice of either "Business" or "Personal". Then create a new page (leave your existing add client page as is) for "add personal client" and "add business client".

@rodolfomartinez FYI

**Comment by rodolfomartinez** [comment]
@KPSbuttar further to this, you can use this drawing - please center the rectangles. Please create this in the folders /jobs/ and /clients/ as create_begin.html
![7bac48bf-d96a-4812-9f1a-cbe46ee0af21](https://user-images.githubusercontent.com/7537946/37258916-76723328-257f-11e8-9049-6714eb6d6c0f.png)

**Comment by rodolfomartinez** [comment]
@KPSbuttar - Residential button should link to http://inthought.pw/clients/client_add.html
Commercial button should link to http://inthought.pw/clients/client_add_comm.html

and in the /jobs folder it should be titled Add Job and URLs should link to
http://inthought.pw/jobs/job_add.html
http://inthought.pw/jobs/job_add_comm.html

Descriptions should be
Add a Residential Job

Add a Commericla Job

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Sir this is Done you can review all here: http://inthought.pw/clients/create_begin.html
