### ISSUE TITLE
UI Change - from 3 to 4 options

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#72]
**Summary:**
For these URLs:
http://inthought.pw/tasks/
http://inthought.pw/jobs/
http://inthought.pw/clients/
http://inthought.pw/members/
http://inthought.pw/team/
http://inthought.pw/partners/

Please remove the edit circle, make the "View" circle a blue background instead of orange, and centre the three cricles.

@bartmika please add any additional feedback

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir all above mentioned pages are updated you can review all are done.
