### ISSUE TITLE
Resources Page

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#73]
**Summary:**

For this page, please make the following changes:

Row 1:
Change first item title to: Forms, change icon to fa-file-alt, change description to: Access forms & documents

Change second item title to: Videos, change icon to fa-youtube, change description to: Access videos & media

Change third item title to: System, change icon fa-cogs, change description to: Access system FAQs.

DELETE all other rows/items, so there should only be three total

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is done you can review here: http://inthought.pw/resources/
