### ISSUE TITLE
Responsive issue with Report/Resource indexes

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#74]
**Summary:**
When using the menu on an ipad, the last column on the right does not scale properly, causing font awesome icons to fall outside the box.

See atatched image for details

![d644022a-b53a-4931-94d6-87eae4590d14](https://user-images.githubusercontent.com/7537946/37259619-d0ba6202-2588-11e8-9cca-b2325100e2a7.jpeg)

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez This Bug is FIXED you can review now.
