### ISSUE TITLE
Add Job Screen 1 - Residential

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#75]
**Summary:**
This screen will have two variants - one for residential jobs and one from commercial jobs, related to #71 

IF this is a Residential job, URL should be inthought.pw/jobs/job_add.html

Title: Add a new Residential Job
Subtitle: Please enter at least one field

and should show the following form:

First Name 
[texfield] 

Last Name
[textfield]

Phone
[texfield]

E-Mail 
[texfield]

<search button - centered>

Please include proper validation

**Comment by KPSbuttar** [comment]
@rodolfomartinez Sir please reply ASAP!
This is Add job form or Search job ?
Why to make "Please enter at least one field" while adding job and "<search button - centered>"?
please clarify. Thanks

**Comment by rodolfomartinez** [comment]
@kpsbuttar this is the firstt step of adding a job - it involves making sure that the customer exists. The workflow is that a customer (either commercial or residential is added) and then a job is created for them. It will look like a search form. @bartmika I guess this means we use a modified retrieve UI and add thr job to that?

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is done please review here: http://inthought.pw/jobs/job_add.html
