### ISSUE TITLE
Add Job Screen 1 - Commercial

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#76]
**Summary:**
This screen will have two variants - one for residential jobs and one from commercial jobs, related to #71 

IF this is a Commercial job, URL should be inthought.pw/jobs/job_add_comm.html

Title: Add a new Commercial Job
Subtitle: Please enter at least one field

and should show the following form:

Company Name
[textfield]

First Name 
[texfield] 

Last Name
[textfield]

Phone
[texfield]

E-Mail 
[texfield]

<search button - centered>

Please include proper validation

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is Add job form or Search job ?
Why to make "Please enter at least one field" while adding job and "<search button - centered>"?
please clarify. Thanks

**Comment by rodolfomartinez** [comment]
Please see my response to #75

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez Its done please review here: http://inthought.pw/jobs/job_add_comm.html
