### ISSUE TITLE
Add Job Screen 2 - Residential

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#77]
**Summary**
For this screen, refer to the following drawing: (Note; back button should be a left arrow, with an orange background, the front button should be a right arrow with a green background) Please note that the controls here are radio buttons. URL should be inthought.pw/jobs/job_add_2.html

![92af6d7e-6cfc-495e-bad4-f9d3e36b87f7](https://user-images.githubusercontent.com/7537946/37259974-ee463c92-258d-11e8-91cc-05dca2a65b08.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is done please review here: 
http://inthought.pw/jobs/job_add_2.html
