### ISSUE TITLE
Add Job Screen 2 - Commercial

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#78]
**Summary**
For this screen, refer to the following drawing: (Note; back button should be a left arrow, with an orange background, the front button should be a right arrow with a green background) Please note that the controls here are radio buttons. URL should be inthought.pw/jobs/job_add_comm_2.html

![ddfaf151-4c50-4176-86b3-2dfb37823264](https://user-images.githubusercontent.com/7537946/37259997-42a17ec8-258e-11e8-8671-0155caa3fec7.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is done see here: http://inthought.pw/jobs/job_add_comm_2.html
