### ISSUE TITLE
Add Residential Job Step 3

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#79]
**Summary:**
Please create this page at inthought.pw/jobs/job_add_3.html

For validation, at least 10 characters must be entered. Input should be a text paragraph box -s ee attached image.

![dad70b18-63d7-407c-8138-66b4537f39a1](https://user-images.githubusercontent.com/7537946/37260083-4e35b6b8-258f-11e8-9f7c-42acb12cfa7c.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez  Its done and validations added please review here: http://inthought.pw/jobs/job_add_3.html
