### ISSUE TITLE
Add Commercial Job Step 3

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#80]
**Summary:**
Please create this page at inthought.pw/jobs/job_add_comm_3.html

For validation, at least 10 characters must be entered. Input should be a text paragraph box - see attached image.
![b1b9fbc5-6309-4197-a67a-4ccfef46ef40](https://user-images.githubusercontent.com/7537946/37260095-6c2d8902-258f-11e8-90d3-a3c886a23826.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez  Its done and validations added please review here: http://inthought.pw/jobs/job_add_comm_3.html
