### ISSUE TITLE
Add Commercial Job Screen 4

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#82]
**Summary:**
This screen should be at URL:
inthought.pw/jobs/job_add_comm_4.html

See following drawing for reference. Items should be tag cloud - we can use this library (unless if @bartmika has any objections) :
https://yaireo.github.io/tagify/
Tags should be bigger with big white text, blue background

For validation, at least ONE tag must be entered.

![8d22b3b9-faed-44b7-8b4b-a741c9382e77](https://user-images.githubusercontent.com/7537946/37260245-01cdf2fc-2591-11e8-92ae-b6097fe012a0.png)

**Comment by KPSbuttar** [comment]
Hi, @rodolfomartinez @bartmika finally this is done taken time to code and implement typeahead script with skills library into tagcloud codes just like sample link you shown. So ALL done. please review here: 
http://inthought.pw/jobs/job_add_comm_4.html

Also sir to add more skills tags options by admin simply add tags to skills.json file in assets/js folder.
