### ISSUE TITLE
Add Residential Job Screen 5

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#83]
**Summary:**
This should be a read only page, which should look like the image below and be at the URL inthought.pw/jobs/job_add_5.html

![bc89d529-94b3-49bc-810e-5b23d4f0ab7d](https://user-images.githubusercontent.com/7537946/37260331-442842a0-2592-11e8-8658-92f9e2899379.png)

Once the user hits the submit button, there should be a nice modal - like a sweet alert - saying

This will create a new job, which will need to be assigned to a member. Do you want to continue? <yes> <no>

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is done please review here: http://inthought.pw/jobs/job_add_5.html
