### ISSUE TITLE
Add Commercial Job Screen 5

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#84]
**Summary:**
This should be a read only page, which should look like the image below and be at the URL inthought.pw/jobs/job_add_comm_5.html

![989600e3-6e14-4adf-90f6-8f2c48ea15c9](https://user-images.githubusercontent.com/7537946/37260384-af9d64a2-2592-11e8-8640-ae9acff56bdd.png)

Once the user hits the submit button, there should be a nice modal - like a sweet alert - saying

This will create a new job, which will need to be assigned to a member. Do you want to continue?

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez This is DONE please review here: http://inthought.pw/jobs/job_add_comm_5.html
