### ISSUE TITLE
Countries & Province/State List

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#85]
**Summary:**
For v1.0, approx 15 countries will be supported (including key launch areas). In the future, we should consider expanding to include more countries.

**Comment by bartmika** [comment]
We'll need to take into account provinces per country as well.

**Comment by rodolfomartinez** [comment]
@bartmika - can we close this? Otherwise please edit ticket and re-assign to @KPSbuttar
