### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#87]
**Summary:**
At this URL http://london.o55.me/en/jobs/create/step-1/search-results?given_name=&last_name=Smith&telephone=
can we have results fit in columns of 3 (rather than 1) on devices with same resolution as an iPad pro?

See attached screen:
![d766a52b-6558-4a12-9327-fcf368438944](https://user-images.githubusercontent.com/7537946/38386541-f36ca8ba-38e2-11e8-8947-964cc44e30f3.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir this Fix is done here at inthought template please review here: 
http://inthought.pw/clients/client_add_1.html

But if you want to fix that template UI  http://london.o55.me Please send me that UI template page url or directory link so will fix in that live project.

Thanks
