### ISSUE TITLE
Create Notes/Comments Page

### ISSUE THREAD

**Issue by rodolfomartinez** [MikaSoftware/inthought#88]
**Summary:**
Hi @KPSbuttar we need to create a "notes" page which will look like a comment system. Please place in inthought.pw/extras/notes.html. It needs to ahve read only comments at the top, and then the user can scroll down and have a paragraph textfield with a button that says "Add Note"

See this screen for inspiration (headshots are not required but nice to have, there should be a full date instead of 5 days ago, time stamp beneath the date. We do not need like or share links.

![3766d413-416b-46f8-834c-b85da09f986c](https://user-images.githubusercontent.com/7537946/39162764-18fd6c84-4745-11e8-8904-e1a63accbdb6.png)

**Comment by bartmika** [comment]
Here is how our comments page looks in overfiftyfive.

![screen shot 2018-04-27 at 11 53 20 pm](https://user-images.githubusercontent.com/5767602/39391736-4c65e6da-4a76-11e8-9196-8cc47a627fb4.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir, this new comments/Notes UI screen is complete with single and nested comments all done. You can review here: inthought.pw/extras/notes.html 
Also now @bartmika sir you can complete this as well https://github.com/over55/overfiftyfive-django/issues/61 . Hope all ok tell me if any tweaks to do for this screen. Thanks

**Comment by bartmika** [comment]
@KPSbuttar Thank you Kanwar.
