### ISSUE TITLE
Error Box at top of form

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought#89]
Hi @KPSbuttar ,

Please implement somesort of error sumamry box which exists on top of the form. Here is an example:

![860bb0585aec1509292591d49003fbaa](https://user-images.githubusercontent.com/5767602/39391090-44801512-4a6c-11e8-8840-e3d7bdcc93d0.jpg)
Please don't remove any existing validation, I want to see this box in one page. 

@rodolfomartinez FYI

**Comment by rodolfomartinez** [comment]
@bartmika - I am referenced in the related issue on Over55. What do I need to do here?

**Comment by bartmika** [comment]
@rodolfomartinez  Oh I see, so I was hoping you can prioritize Kanwar to implement this task but before you do, can you recommend him a design you like? I've added a screenshot of a error prompt which looks good but I'd like your final say on this matter.

**Comment by rodolfomartinez** [comment]
I agree.- let's use this as an inspiration

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir, so finally Validations and error handling NEW DESIGN is done and validations jquery has updated. All done you can test and check validations now. Please review all here: http://inthought.pw/clients/client_add.html
Now you can proceed with https://github.com/over55/overfiftyfive-django/issues/80 This Issue in Over55 project. Thanks
Tell me if any more tweaks to do for this screen.

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika  Also sir you can check http://inthought.pw/clients/client_add.html
here all minimum 3 char, invalid phone number etc all validations while filling the form validation error message will gets updated accordingly.

**Comment by bartmika** [comment]
@KPSbuttar Thank you Kanwar, I confirm I see your most recent change. I will implement today.
