### ISSUE TITLE
More Icons?

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought#91]
Hey @rodolfomartinez, 

What do you think about adding more icons here? (See circles)

![screen shot 2018-05-23 at 9 43 51 pm](https://user-images.githubusercontent.com/5767602/40460036-c145aff6-5ed2-11e8-9e86-db9c5e69cbf8.png)

**Comment by rodolfomartinez** [comment]
I think this is good for now, but what did you have in mind @bartmika ?
