### ISSUE TITLE
Refactoring & New Architecture

### ISSUE THREAD

**Issue by bartmika** [MikaSoftware/inthought#93]
Hello Kanwar (@KPSbuttar).

This theme is going to have a new architecture. Here is how it will work.

# /html
This will be the core, components, js, css, etc folder which this theme. This folder will also contain our styleguide. This folder is never specific to any project but a core folder.

# /project
This will be the project specific folder we will use to create our screens. Our projects will use the core `/html` css code to power the mockups.

Whenever we start a new project, we clone this repo (https://github.com/MikaSoftware/inthought/) and populate this `/project` folder for the fork.

Currently we have done this for the following:
* https://github.com/LuchaComics/inthought-comicscantina
* https://github.com/over55/inthought-workery

# Notes:
* Every-time you update this project, you will need to update the dependent projects (ex: inthought-comicscantina)

* Every-time you create project specific CSS changes, you override the existing CSS and place your override in the `project` folder

* If you add a new feature or GUI which should be in the core then update the `html` folder.

* Why are we doing this? (1) We want this repo to be a ready-to-use open source theme which we can easily clone to other projects and build GUI with. (2) When we make fixes / upgrades to the change to the core, all the forked projects will inherit the changes that come downstream from this core theme.

# What do I do next?
@KPSbuttar  Please update this library to support our new architecture. If you have any questions, please ask me in this ticket.

@rodolfomartinez If you are good with this direction, please confirm in the ticket.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez All completed sir, please review. Thanks
